Fe add folders
TPT-Loane/TPT-Loane pull request #27
Opened 2021-04-20 08:27 UTC by tomimarkus991

1. Updated folders
2. Added more strict ts config
3. removed react import as it is not needed after V17 on React
4. Fixed eslint devdependency error
5. added dev script

2021-04-20 09:04 UTC, GeorgDV requested changes

2021-04-20 09:04 UTC, GeorgDV commented on fe/src/pages/About/About.tsx
> -import React from 'react';
I'm not sure about removing `react` imports, altough true, that its not required for react to work.
IMHO this rises more problems with eslint than fixes, so i'd say we should add the imports back. 🤔 
![errors](https://user-images.githubusercontent.com/48998862/115368874-30448b00-a1d0-11eb-8004-e458f1b07a75.JPG)

2021-04-20 09:10 UTC, GeorgDV commented on fe/src/pages/About/About.tsx
> -import React from 'react';
Actually when i restarted local project the errors were gone, so the `react/react-in-jsx-scope`  rule works after all.

I'd say then we can leave the imports as they now are.

2021-04-20 10:05 UTC, Kasparsu commented on fe/src/App.tsx
> +import Error from './pages/Error/index';
just to note that both are okay structures and I proposed both of them. However it was allready agreed that we are going with the structure @GeorgDV mentioned above.

2021-04-20 10:08 UTC, Kasparsu commented
Before merging fixup commits. commits that have sole purpose of fixing your past mistakes should not end up in main. you can do interactive rebase and then squash or fixup commits and even reorder them if need be. https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase

2021-04-20 10:36 UTC, tomimarkus991 commented on fe/src/App.tsx
> +import Error from './pages/Error/index';
Having a specific folder for route-level components to be placed is a good practice. It also sets a clear hierarchy of differentiation between pages and components, where a page can import a component to display it and do nothing else, not even Business Logic.

You can also read [this](https://www.freecodecamp.org/news/a-better-way-to-structure-react-projects/)

2021-04-20 11:01 UTC, GeorgDV commented on fe/src/App.tsx
> +import Error from './pages/Error/index';
I guess both of them can be useful structures, but it is already planned upon current structure, as said. In current hierarchy there is still a set difference between page components and other components, but its just differently structured.

2021-04-21 19:18 UTC, Kasparsu commented on fe/src/App.tsx
> +import Error from './pages/Error/index';
If I think about it a while. this change actually makes bit more sense. I would suggest we change the structure proposed here. @GeorgDV change is quite small and it works either way. But having pages and layouts folders and then bunch of loose component folders all mixed up might actually be bad idea. So maybe yeah leave components folder for loose components. either reusable or single use but pages and layouts are their own separate things.

2021-04-21 20:10 UTC, Kasparsu commented on fe/src/App.tsx
> +import Error from './pages/Error/index';
maybe can get @Orzelius opinion here?

2021-04-21 20:31 UTC, Orzelius commented on fe/src/App.tsx
> +import Error from './pages/Error/index';
This has long deviated from the structure I'm familiar with so I can't really say. Usually in react everything is a component and the topmost ones might happen to be pages as well.

In the article Tomi linked, an indea of multiple contexts was brought up, which I'm not really familiar with. Usually there's one global context and then further state shared between components. 

But all in all I think we can go with this approach (proposed in this pr). Seems like it's a bit more React-friendly and requires less inventing.

2021-04-22 06:55 UTC, Kasparsu approved these changes

2021-04-22 07:53 UTC, Kasparsu commented on fe/src/App.tsx
> +import Error from './pages/Error/index';
@GeorgDV maybe then resolve and merge?

2021-04-22 08:31 UTC, GeorgDV commented on fe/src/App.tsx
> +import Error from './pages/Error/index';
Alrighty then, we'll go with this structure. 👍

2021-04-22 08:32 UTC, GeorgDV approved these changes

2021-04-22 08:46 UTC, GeorgDV commented
@tomimarkus991 This branch has conflicts so they need fixing before merging.

Also with the new structure could you please update that [this](https://github.com/TPT-Loane/TPT-Loane/pull/31) added eslint rule works with the new directory structure?
Basically you only need changes [here ](https://github.com/TPT-Loane/TPT-Loane/pull/31/files#diff-ace789a57d4e936793d1f602a82b8210450c3f0470a940391084a527bfdda75fR39)in "allow" field to correspond with new directories, so that imports like **'./pages/Home**' are **allowed** (./pages/*), etc.

2021-04-22 16:34 UTC, tomimarkus991 commented
> 
> 
> @tomimarkus991 This branch has conflicts so they should be fixed and rebased.
> 
> Also with the new structure could you please update that [this](https://github.com/TPT-Loane/TPT-Loane/pull/31) added eslint rule works with the new directory structure?
> Basically you only need changes [here ](https://github.com/TPT-Loane/TPT-Loane/pull/31/files#diff-ace789a57d4e936793d1f602a82b8210450c3f0470a940391084a527bfdda75fR39)in "allow" field to correspond with new directories, so that imports like **'./pages/Home**' are **allowed** (./pages/*), etc.

will do

2021-04-22 17:10 UTC, merged