Add improved env example and changed env variables
TPT-Loane/TPT-Loane pull request #43
Opened 2021-04-23 11:16 UTC by Erikyy

2021-04-23 11:17 UTC, Orzelius commented
Is this supposed to be WIP (draft)?

2021-04-23 11:19 UTC, Erikyy commented
> Is this supposed to be WIP (draft)?

Nah, it is quite small task and I just finished it.

2021-04-23 11:23 UTC, Orzelius commented
> Nah, it is quite small task and I just finished it.

Ah, okay, then be sure to mention somewhere that it closes #43

2021-04-23 11:33 UTC, Orzelius requested changes

2021-04-23 11:33 UTC, Orzelius commented on be/.env.example
> +SERVER_PORT=3000
Add eol and change the port (front end already uses 3000)

2021-04-23 11:33 UTC, Orzelius commented on be/.env.example
> +DATABASE_IP=0.0.0.0
Maybe change to `127.0.0.1.` so it would immediately work with the docker db setup

2021-04-23 11:36 UTC, Orzelius commented
Also your git signature seems off, this makes it so github is confused about your commits and doesn't assign them to your github user. See how the commiter and your github profile seem to be different.
![image](https://user-images.githubusercontent.com/33936483/115865530-207fad80-a441-11eb-9ebe-b144a01c0df8.png)

You can read the docs and howto [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification)

2021-04-23 11:57 UTC, Orzelius submitted a review, later dismissed

2021-04-23 11:58 UTC, Orzelius commented
wait what a74fe76?

2021-04-23 12:11 UTC, Erikyy commented
> wait what [a74fe76](https://github.com/TPT-Loane/TPT-Loane/commit/a74fe7659693b81ab3b37e0cd6021e69e76fbc5a)?

Accidently again, forgot to sign

2021-04-23 12:34 UTC, Orzelius commented
Maybe your git and github emails are different or you haven't added one to another?

2021-04-23 12:35 UTC, Erikyy commented
> Maybe your git and github emails are different or you haven't added one to another?

I'm quite sure that I use my own email for signatures

2021-04-23 12:38 UTC, Erikyy commented
There, turns out that I had wrong email in git config
![face-palm](https://user-images.githubusercontent.com/50318528/115872014-f7174f80-a449-11eb-851b-817f9ccce2d5.jpeg)

2021-04-23 12:40 UTC, Orzelius commented
yay, it's green now
![image](https://user-images.githubusercontent.com/33936483/115872253-41003580-a44a-11eb-98a2-3d7ae95420a3.png)

2021-04-23 12:41 UTC, Orzelius approved these changes

2021-04-25 21:23 UTC, Kasparsu approved these changes
Yeah this looks like a good .env.example file right there. No gripes what so ever!

2021-04-26 05:28 UTC, merged