Add notes
TPT-Loane/TPT-Loane pull request #88
Opened 2021-05-14 06:52 UTC by tuulingo

## Header
Add notes #68 

## Description

- [] Add operations for notes (create, read, delete). Didn't include update, because we don't want it.
- [] Commented "Item" structure will be fixed in another branch

Fixes #68 notes data structure

## Branch name

Add-notes

2021-05-14 07:18 UTC, Orzelius requested changes
Some small changes would be nice.

This pr was structured a bit weird. You should had named the fields `note` straight away and not had a commit that changed the names. Also Let's commit all gen code (schema, migrations) separately as there's no point in reviewing it.

2021-05-14 07:18 UTC, Orzelius commented on be/src/note/dto/update-note.input.ts
> +export class UpdateNoteInput {
The `UpdateNoteInput` and `CreateNoteInput` classes are the same currently. Might as well have only one for now

2021-05-14 07:18 UTC, Orzelius commented on be/src/note/entities/note.entity.ts
> +    @Column({ length: 255, nullable: false })
This length might be not enough. Some people might want to have lengthy notes 🤷

2021-05-14 07:18 UTC, Orzelius commented on be/src/note/note.service.ts
> +  //  }
Some leftover code? Plz remove

2021-05-14 08:15 UTC, Orzelius approved these changes

2021-05-14 08:56 UTC, Orzelius requested changes

2021-05-14 08:56 UTC, Orzelius commented on be/src/note/dto/create-note.input.ts
> +    @Column({ nullable: false })
Oh wait, I did a lazy review, this shouldn't be here. the `@Column` decorator come from `typeorm` package and has nothing to do with gql input object. `@Column` is used in typeorm entities do describe db structure. This class here describes the input needed to gql to create a new Note.

2021-05-14 09:52 UTC, Orzelius approved these changes

2021-05-14 09:54 UTC, Orzelius commented on be/src/note/dto/create-note.input.ts
> +    @Column({ nullable: false })
Fixed -> 6066234

2021-05-14 09:55 UTC, Orzelius commented
@tuulingo fyi when fixing things up from reviews then it's easier for the reviewer if separated each review request change into separate commit (Like you did with 6066234) and comment to the review-comment what you changed with the commit hash (like [this](https://github.com/TPT-Loane/TPT-Loane/pull/88#discussion_r632419235))

2021-05-16 09:23 UTC, tomimarkus991 approved these changes

2021-05-17 06:33 UTC, Erikyy approved these changes

2021-05-21 05:53 UTC, merged