Fe add possibility to switch between dark and light theme
TPT-Loane/TPT-Loane pull request #95
Opened 2021-05-17 07:49 UTC by Kahuka

Fe add possibility to switch between dark and light theme #69 
```
- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update
```

2021-05-17 08:04 UTC, Orzelius requested changes
Overall nice but some small things:
1. The sun icon looks like settings icon to me, might be a bit confusing (and unpleasant if clicked in the dark)
2. Next time make the commits pretty right away 🛩️

2021-05-17 08:04 UTC, Orzelius commented on fe/src/components/Header/Header.tsx
> +          <IconButton
Could you add on-hover here that will say either `Switch to light theme` or `Switch to dark theme`

2021-05-17 08:51 UTC, tomimarkus991 commented
Do we want the colormode button to be reusable?
If yes then Kahuka should make it a separate component

2021-05-17 08:57 UTC, Orzelius commented
> 
> 
> Do we want the colormode button to be reusable?
> If yes then Kahuka should make it a separate component

That's a good point. Probably the same button will be used in the settings so it makes sense to have it as a separate component.

2021-05-18 07:23 UTC, tomimarkus991 commented
Good job, but I don't think Colormode.tsx should be under styles folder. @GeorgDV where should it be?

2021-05-18 07:32 UTC, GeorgDV commented
> Good job, but I don't think Colormode.tsx should be under styles folder. @GeorgDV where should it be?

Since its a new component, it should go under `components` folder:
```
components/ColorMode/ColorMode.tsx
// and also for exporting..
components/ColorMode/index.ts
```

2021-05-18 07:38 UTC, GeorgDV requested changes
Nice, but i noticed a thing aswell.

2021-05-18 07:38 UTC, GeorgDV commented on fe/src/components/Header/Header.tsx
> +        <HStack spacing={12} ml="auto" title={colorMode === 'light' ? 'Switch to dark theme' : 'Switch to light theme'}>
Also as you can see, this is  exact copy-paste of the component code from `ColorMode.tsx`, why copy existing code, if we could already use it here. You could import the new component in this file and then use it here as one line:
```
<ColorMode />
```

2021-05-18 11:57 UTC, tomimarkus991 commented on fe/src/components/ColorMode/ColorMode.tsx
> +    <HStack spacing={12} ml="auto" title={colorMode === 'light' ? 'Switch to dark theme' : 'Switch to light theme'}>
Make it so that ColorMode component only has IconButton. HStack should stay on Header

2021-05-18 11:58 UTC, tomimarkus991 commented on fe/src/components/ColorMode/ColorMode.tsx
> +import { FaMoon, FaSun } from 'react-icons/all';
Can you use ChakraIcons for Sun and Moon, because I want to remove react-icons in the future #96

2021-05-24 06:29 UTC, tomimarkus991 commented on fe/src/components/Header/Header.tsx
> +        <HStack spacing={12} ml="auto" title={colorMode === 'light' ? 'Switch to dark theme' : 'Switch to light theme'}>
title should be inside Colormode.tsx component, because right now every element in HStack has this onHover title.

2021-05-24 06:39 UTC, Orzelius commented
What are these commit messages?  :D

2021-05-24 09:50 UTC, Orzelius approved these changes

2021-05-24 10:54 UTC, tomimarkus991 submitted a review, later dismissed

2021-05-25 06:54 UTC, GeorgDV approved these changes

2021-05-25 08:18 UTC, GeorgDV approved these changes

2021-05-25 22:56 UTC, merged